import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Easing } from 'react-native-reanimated';
import { AppColors } from '@/constants/colors';

export const ORANGE = AppColors.orange;
export const ORANGE2 = '#cc5500';
export const BG = '#080808';
export const TEXT = '#f0ede8';
export const MUTED = 'rgba(240,237,232,0.42)';
export const HINT = 'rgba(240,237,232,0.18)';
export const IS_ANDROID = Platform.OS === 'android';
export const SCREEN_WIDTH = Dimensions.get('window').width;

const st = StyleSheet.create({
  safe: { flex: 1 },

  header: {
    height: IS_ANDROID ? 54 : 60,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  title: { color: TEXT, fontWeight: '800', fontSize: IS_ANDROID ? 22 : 24, letterSpacing: -0.4 },
  chevronWrap: {
    backgroundColor: 'rgba(255,120,37,0.14)',
    borderRadius: 7,
    padding: 5,
    borderWidth: 0.5,
    borderColor: 'rgba(255,120,37,0.25)',
  },
  actions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: {
    width: IS_ANDROID ? 36 : 38,
    height: IS_ANDROID ? 36 : 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: ORANGE,
    borderWidth: 1.5,
    borderColor: BG,
  },
  syncBtn: {
    width: IS_ANDROID ? 36 : 38,
    height: IS_ANDROID ? 36 : 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncBtnActive: {
    backgroundColor: 'rgba(255,107,53,0.14)',
    borderColor: 'rgba(255,107,53,0.35)',
  },

  list: { paddingHorizontal: 14, paddingTop: IS_ANDROID ? 6 : 8, paddingBottom: 100 },

  card: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.08)',
    position: 'relative',
  },
  cardShine: { position: 'absolute', top: 0, left: 0, right: 0, height: 1 },
  cardAccentBar: { height: 2, width: '40%', borderBottomRightRadius: 2 },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: 12,
    gap: IS_ANDROID ? 8 : 10,
  },
  avatarWrap: { position: 'relative' },
  avatar: {
    width: IS_ANDROID ? 36 : 40,
    height: IS_ANDROID ? 36 : 40,
    borderRadius: IS_ANDROID ? 18 : 20,
    backgroundColor: '#1a1a1a',
    borderWidth: 2,
    borderColor: 'rgba(255,120,37,0.4)',
  },
  avatarOnline: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#34c759',
    borderWidth: 1.5,
    borderColor: BG,
  },
  username: { color: TEXT, fontWeight: '700', fontSize: IS_ANDROID ? 13 : 14 },
  time: { color: MUTED, fontSize: IS_ANDROID ? 11 : 12, marginTop: 1 },
  followBtnText: { color: ORANGE, fontSize: IS_ANDROID ? 11 : 12, fontWeight: '700' },
  postTitle: {
    color: TEXT,
    fontSize: IS_ANDROID ? 16 : 17,
    fontWeight: '700',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  caption: {
    color: 'rgba(240,237,232,0.88)',
    fontSize: IS_ANDROID ? 14 : 15,
    lineHeight: IS_ANDROID ? 21 : 23,
    paddingHorizontal: 14,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: IS_ANDROID ? 10 : 12,
    gap: IS_ANDROID ? 16 : 20,
  },
  miniStat: {},
  miniStatLabel: { color: MUTED, fontSize: IS_ANDROID ? 10 : 11, marginBottom: 2 },
  miniStatValue: { color: TEXT, fontWeight: '700', fontSize: IS_ANDROID ? 13 : 14 },
  imageWrap: { position: 'relative', marginHorizontal: 14, borderRadius: 14, overflow: 'hidden' },
  mediaSlide: { overflow: 'hidden' },
  postImage: { width: '100%', height: IS_ANDROID ? 220 : 250, backgroundColor: '#1a1a1a' },
  mediaEmptyWrap: {
    width: '100%',
    height: IS_ANDROID ? 220 : 250,
    backgroundColor: '#151515',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  mediaEmptyIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  mediaEmptyText: {
    color: MUTED,
    fontSize: IS_ANDROID ? 12 : 13,
    fontWeight: '600',
  },
  imageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: IS_ANDROID ? 10 : 12,
    paddingBottom: 4,
  },
  likeBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, marginRight: 14 },
  likeCount: { color: 'rgba(255,255,255,0.7)', fontSize: IS_ANDROID ? 13 : 14, fontWeight: '600' },
  commentBtn: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  commentCount: { color: 'rgba(255,255,255,0.5)', fontSize: IS_ANDROID ? 12 : 13 },
  shareBtn: { padding: 4 },
  likedByRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingBottom: 12,
    gap: 8,
    marginTop: 4,
  },
  tinyAvatar: {
    width: IS_ANDROID ? 18 : 20,
    height: IS_ANDROID ? 18 : 20,
    borderRadius: IS_ANDROID ? 9 : 10,
    backgroundColor: '#1a1a1a',
    borderWidth: 1.5,
    borderColor: BG,
  },
  likedByText: { color: MUTED, fontSize: IS_ANDROID ? 11 : 12, flex: 1 },

  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)' },
  menu: {
    position: 'absolute',
    top: IS_ANDROID ? 64 : 72,
    left: 14,
    width: 250,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  menuBlur: { padding: 6, backgroundColor: 'rgba(10,10,10,0.96)' },
  menuItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 12 },
  menuItemActive: { backgroundColor: 'rgba(255,120,37,0.06)' },
  menuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  menuIconActive: { backgroundColor: 'rgba(255,120,37,0.14)' },
  menuText: { color: 'rgba(255,255,255,0.6)', flex: 1, fontSize: IS_ANDROID ? 14 : 15, fontWeight: '600' },
  menuTextActive: { color: TEXT, fontWeight: '700' },
  activeDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: ORANGE },
  menuDivider: { height: 0.5, backgroundColor: 'rgba(255,255,255,0.07)', marginHorizontal: 10 },

  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBar: {
    flex: 1,
    height: IS_ANDROID ? 42 : 46,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  searchInput: { flex: 1, color: TEXT, fontSize: IS_ANDROID ? 13 : 15, paddingVertical: 0 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: IS_ANDROID ? 11 : 13,
    gap: 12,
  },
  searchAvatarWrap: {
    borderWidth: 1.5,
    borderColor: 'rgba(255,120,37,0.3)',
    borderRadius: IS_ANDROID ? 22 : 24,
    padding: 1.5,
  },
  searchAvatar: {
    width: IS_ANDROID ? 40 : 44,
    height: IS_ANDROID ? 40 : 44,
    borderRadius: IS_ANDROID ? 20 : 22,
    backgroundColor: '#1a1a1a',
  },
  searchName: { color: TEXT, fontWeight: '700', fontSize: IS_ANDROID ? 14 : 15 },
  searchCaption: { color: MUTED, fontSize: IS_ANDROID ? 12 : 13, marginTop: 2 },
  emptySearch: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14, paddingTop: 80 },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: { color: MUTED, fontSize: IS_ANDROID ? 14 : 15 },

  sheetKav: { position: 'absolute', left: 0, right: 0, bottom: 0, top: 0, justifyContent: 'flex-end' },
  commentsSheet: {
    backgroundColor: '#0e0d0b',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
    paddingBottom: IS_ANDROID ? 16 : 20,
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(255,255,255,0.09)',
    maxHeight: '85%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignSelf: 'center',
    marginBottom: 10,
  },
  sheetTitle: {
    color: TEXT,
    fontWeight: '700',
    fontSize: IS_ANDROID ? 15 : 16,
    textAlign: 'center',
    marginBottom: 10,
  },
  commentsList: { maxHeight: IS_ANDROID ? 280 : 340, paddingHorizontal: 14 },
  emptyComments: { alignItems: 'center', justifyContent: 'center', paddingVertical: 30, gap: 10 },
  emptyCommentsText: { color: MUTED, fontSize: IS_ANDROID ? 13 : 14 },
  commentItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: IS_ANDROID ? 10 : 12 },
  commentAvatar: {
    width: IS_ANDROID ? 34 : 38,
    height: IS_ANDROID ? 34 : 38,
    borderRadius: IS_ANDROID ? 17 : 19,
    backgroundColor: '#1a1a1a',
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255,120,37,0.3)',
  },
  commentTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  commentUser: { color: TEXT, fontWeight: '700', fontSize: IS_ANDROID ? 13 : 14 },
  commentTime: { color: MUTED, fontSize: IS_ANDROID ? 11 : 12 },
  commentText: {
    color: 'rgba(240,237,232,0.8)',
    fontSize: IS_ANDROID ? 13 : 14,
    lineHeight: IS_ANDROID ? 19 : 21,
  },
  commentActions: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  replyBtn: { paddingVertical: 2 },
  replyBtnText: { color: ORANGE, fontSize: IS_ANDROID ? 11 : 12, fontWeight: '700' },
  viewRepliesBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  viewRepliesText: { color: ORANGE, fontSize: IS_ANDROID ? 11 : 12, fontWeight: '600' },
  commentLikeRow: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingLeft: 8, paddingTop: 2 },
  commentLikeCount: { color: 'rgba(255,255,255,0.4)', fontSize: 11 },
  commentDivider: { height: 0.5, backgroundColor: 'rgba(255,255,255,0.05)' },
  replyItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
    paddingLeft: 14,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(255,120,37,0.2)',
  },
  replyAvatar: {
    width: IS_ANDROID ? 26 : 28,
    height: IS_ANDROID ? 26 : 28,
    borderRadius: IS_ANDROID ? 13 : 14,
    backgroundColor: '#1a1a1a',
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,120,37,0.25)',
  },
  replyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: 'rgba(255,120,37,0.08)',
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(255,120,37,0.15)',
  },
  replyBannerText: { flex: 1, color: 'rgba(255,255,255,0.6)', fontSize: IS_ANDROID ? 12 : 13 },
  emojiRow: {
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(255,255,255,0.06)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: IS_ANDROID ? 10 : 12,
    paddingBottom: IS_ANDROID ? 8 : 10,
    marginTop: 4,
  },
  emojiBtn: { paddingHorizontal: 2 },
  emojiText: { fontSize: IS_ANDROID ? 22 : 26 },
  commentInputBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 10 },
  commentInputGrad: {
    flex: 1,
    height: IS_ANDROID ? 46 : 50,
    borderRadius: IS_ANDROID ? 23 : 25,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  commentInput: {
    flex: 1,
    color: TEXT,
    paddingHorizontal: 18,
    fontSize: IS_ANDROID ? 14 : 15,
    height: '100%',
  },
  sendBtn: {
    width: IS_ANDROID ? 46 : 50,
    height: IS_ANDROID ? 46 : 50,
    borderRadius: IS_ANDROID ? 23 : 25,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: ORANGE,              // make send button visible
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  mediaDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
    marginBottom: 2,
  },
  mediaDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.26)',
  },
  mediaDotActive: {
    width: 18,
    backgroundColor: ORANGE,
  },
  videoHint: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  videoHintText: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '700',
  },
    exerciseSlide: {
    height: IS_ANDROID ? 220 : 250,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: '#121212',
    },
    exerciseSlideSingle: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    },
    singleExerciseContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    },
    singleExerciseIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    },
    singleExerciseIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    },
    singleExerciseSetsText: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
    },
    singleExerciseNameText: {
    color: 'rgba(240,237,232,0.86)',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    },
    exerciseCard: {
    marginHorizontal: 14,
    marginTop: 10,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.08)',
    },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    gap: 8,
  },
  exerciseIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  exerciseIcon: {
    width: '100%',
    height: '100%',
  },
  exerciseSetsText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
    minWidth: 48,
  },
  exerciseNameText: {
    flex: 1,
    color: 'rgba(240,237,232,0.86)',
    fontSize: 12,
    fontWeight: '600',
  },
  exerciseEmptyText: {
    color: MUTED,
    fontSize: 12,
    paddingVertical: 6,
  },
  moreExercisesBtn: {
    paddingTop: 4,
    paddingBottom: 2,
  },
  moreExercisesText: {
    color: MUTED,
    fontSize: 12,
    fontWeight: '600',
  },
  loadMoreWrap: {
    paddingTop: 14,
    paddingBottom: 4,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadMoreText: {
    color: MUTED,
    fontSize: 12,
    fontWeight: '600',
  },
});

export default st;

